### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by vipinsingh211** [GreenFlag31/carousel-library#5]
$ npm i ngx-carousel-ease --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxx
npm ERR! Found: @angular/common@18.2.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0" from ngx-carousel-ease@0.1.4
npm ERR! node_modules/ngx-carousel-ease
npm ERR!   ngx-carousel-ease@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by GreenFlag31** [comment]
Hi

Thank you for your ticket, I will add V18 support asap.

Cheers

**Comment by GreenFlag31** [comment]
See v0.1.5.
