### ISSUE TITLE
Carousel Service returns incorrect onSlideChange number when infinite = true

### ISSUE THREAD

**Issue by nathan-phntm** [GreenFlag31/carousel-library#8]
Angular index and item go 0 --> 6 and then back to 0 again.
Service gets to 6 then always returns 6.

Link to repo: https://stackblitz.com/edit/stackblitz-starters-ogdurd?file=src%2Fapp%2Fcarousel%2Fcarousel.component.html

**Comment by GreenFlag31** [comment]
I will look at this (I think minor) issue and come back to you asap.
Don't hesitate to fork and propose a PR if you want to contribute :)

**Comment by nathan-phntm** [comment]
I forked the repo and tried to replicate but it's working as expected on master

**Comment by GreenFlag31** [comment]
I think the problem lies in the `track` Angular (function). I have added a console.log and the value is correctly reset to 0 after last slide. Btw, if you put an `async` inside a `@for` loop, you will create multiple subscriptions, which is not very optimal.
