### ISSUE TITLE
Resizing screen scrolls carousel to the first slide.

### ISSUE THREAD

**Issue by Gvero98** [GreenFlag31/carousel-library#9]
When you resize screen, carousel scrolls to the first slide...but also, sometimes when you scroll on phone, same thing happens. Is there any way to disable this?

**Comment by GreenFlag31** [comment]
Hi.

As far as I remember, keeping the scroll position while resizing would involve a lot of computations. I have seen other libraries behaving the same way. However, having it return to the first slide when you scroll on mobile is not normal. Could you share your HTML or a reproducible example?

**Comment by Gvero98** [comment]
Hi. 

I just tried it on demo page : [here](https://greenflag31.github.io/carousel-library/ngx-carousel-ease) and same thing happens:


https://github.com/user-attachments/assets/4ccd12ee-36fa-4273-8e56-7223ffa86f15

Same thing happens to all other carousels as well :(

**Comment by GreenFlag31** [comment]
Already thanks, I will have a look asap (certainly next week). Seems that the vertical scrolling is considered as an horizontal scrolling, which then trigger the effect.

**Comment by GreenFlag31** [comment]
Could you try the v0.1.6 ? It should be fixed.

**Comment by Gvero98** [comment]
Yep. It's ok now. Well done. :)
